# -*- coding: utf-8 -*-
"""Steam API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QE_WjPfnozG55DCumiqb76EqsRWRmq2l
"""

import requests
import pandas as pd
import time

# Put your details here
API_KEY = "API KEY"  # paste your Steam API key
STEAM_ID = "STEAM ID"  # we'll get this in a sec

url = f"http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key={API_KEY}&steamids={STEAM_ID}"

response = requests.get(url)

print(response.status_code)
print(response.json())

games_url = f"http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key={API_KEY}&steamid={STEAM_ID}&include_appinfo=true&format=json"

games_response = requests.get(games_url)

games_data = games_response.json()

print(games_data)

games_list = games_data['response']['games']

df = pd.DataFrame(games_list)

df['playtime_hours'] = df['playtime_forever'] / 60

df = df[['name', 'playtime_forever', 'playtime_hours']]

df = df.sort_values(by='playtime_hours', ascending=False)

df = df.reset_index(drop=True)

df

df[df['name'].str.contains('Hero', case=False)]

import matplotlib.pyplot as plt

top10 = df.head(10)

plt.figure(figsize=(12, 6))

plt.barh(top10['name'], top10['playtime_hours'], color='steelblue')

plt.xlabel('Playtime (Hours)')
plt.title('Nafu - Top 10 Most Played Steam Games')
plt.gca().invert_yaxis()

plt.tight_layout()
plt.show()

"""INSIGHT:



**1.   What does this tell me?**

Most of my top 10 games are fighting genre


**2. Why is this happening?**

Because I love fighting games
Anyone looking at the visual can assume I'm a fighting game fan


**3. What should I look at next?**

Top 2 games (NARAKA & Street Fighter V) have significantly more hours than the rest
Shows that fighting games take up a huge chunk of my total playtime

# **Last played analysis — which games did I abandon vs still playing?**
"""

import datetime

df_full = pd.DataFrame(games_list)

df_full['playtime_hours'] = df_full['playtime_forever'] / 60

df_full['last_played'] = pd.to_datetime(df_full['rtime_last_played'], unit='s')

today = pd.Timestamp.now()

df_full['days_since_played'] = (today - df_full['last_played']).dt.days

df_full = df_full[['name', 'playtime_hours', 'last_played', 'days_since_played']]

df_full = df_full[df_full['playtime_hours'] > 0]

df_full = df_full.sort_values(by='days_since_played', ascending=True)

df_full = df_full.reset_index(drop=True)

df_full

steam_profile = response.json()['response']['players'][0]

print(steam_profile)

account_created = pd.to_datetime(steam_profile['timecreated'], unit='s')

today = pd.Timestamp.now()

account_age = (today - account_created).days

print(f"Steam account created on: {account_created.date()}")
print(f"Account age: {account_age} days")
print(f"That is roughly {round(account_age / 365, 1)} years")

appid = 413150  # Stardew Valley

url = f"https://store.steampowered.com/api/appdetails?appids={appid}&cc=us&l=en"
response = requests.get(url)
data = response.json()

print(data)

import time
import requests
import pandas as pd

# Rebuild df_full with appid
df_full = pd.DataFrame(games_list)
df_full['playtime_hours'] = df_full['playtime_forever'] / 60
df_full['last_played'] = pd.to_datetime(df_full['rtime_last_played'], unit='s')
today = pd.Timestamp.now()
df_full['days_since_played'] = (today - df_full['last_played']).dt.days
df_full = df_full[['appid', 'name', 'playtime_hours', 'last_played', 'days_since_played']]
df_full = df_full[df_full['playtime_hours'] > 0]
df_full = df_full.sort_values(by='days_since_played', ascending=True)
df_full = df_full.reset_index(drop=True)

# Fetch genres
genre_map = {}

for index, row in df_full.iterrows():
    appid = int(row['appid'])
    url = f"https://store.steampowered.com/api/appdetails?appids={appid}&cc=us&l=en"
    response = requests.get(url)
    data = response.json()

    try:
        genre_list = [g['description'] for g in data[str(appid)]['data']['genres']]
        genre = ', '.join(genre_list)
    except Exception as e:
        genre = 'Unknown'
        print(f"❌ {row['name']} failed: {e}")

    genre_map[appid] = genre
    print(f"✅ {row['name']} — {genre}")
    time.sleep(2)

df_full['genre'] = df_full['appid'].map(genre_map)
df_full[['name', 'genre']]

all_genres = df_full['genre'].str.split(', ').explode()

genre_counts = all_genres.value_counts()

print(genre_counts)

"""The Highest genre count for this player is Action.
So we can assume that this player loves action game.
So as a seller we know that we can make campaign related to action genre.
"""

# Explode genres and match with playtime
df_exploded = df_full.assign(genre=df_full['genre'].str.split(', ')).explode('genre')

# Group by genre and sum playtime
genre_playtime = df_exploded.groupby('genre')['playtime_hours'].sum().sort_values(ascending=False)

print(genre_playtime)

plt.figure(figsize=(10, 8))

plt.pie(genre_playtime.values,
        labels=genre_playtime.index,
        autopct='%1.1f%%',
        startangle=140)

plt.title('Nafu — Playtime Distribution by Genre')
plt.axis('equal')
plt.show()

"""Top 3 genre:
1. Action
2. Adventure
3. Massively Multiplayer


Action dominates mostly because Steam labels fighting games as Action. The high Free to Play playtime suggests this player is a low spender — probably a student or not working yet.
"""

# Get top 10 games by playtime
top10 = df_full.nlargest(10, 'playtime_hours')

# Explode genres for top 10
top10_exploded = top10.assign(genre=top10['genre'].str.split(', ')).explode('genre')

# Get unique genres for coloring
unique_genres = top10_exploded['genre'].unique()

# Create color map
colors = plt.cm.Set3.colors
genre_color = {genre: colors[i % len(colors)] for i, genre in enumerate(unique_genres)}

# Plot
fig, ax = plt.subplots(figsize=(14, 7))

bottom = pd.Series([0.0] * len(top10), index=top10.index)

for genre in unique_genres:
    genre_data = top10_exploded[top10_exploded['genre'] == genre].set_index('name')['playtime_hours']
    genre_data = genre_data.reindex(top10['name']).fillna(0) / top10_exploded.groupby('name')['playtime_hours'].first().reindex(top10['name'])
    heights = top10.set_index('name')['playtime_hours'] * genre_data.values
    ax.bar(top10['name'], heights, bottom=bottom.values, label=genre, color=genre_color[genre])
    bottom = bottom + heights.values

ax.set_xlabel('Game')
ax.set_ylabel('Playtime (Hours)')
ax.set_title('Nafu — Top 10 Games Playtime by Genre')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Genre', bbox_to_anchor=(1.05, 1))
plt.tight_layout()
plt.show()